/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cabin {
  'id' : bigint,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'stage' : string,
  'notes' : string,
  'cabinType' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
  'startDate' : string,
}
export interface CabinInput {
  'stage' : string,
  'notes' : string,
  'cabinType' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
  'startDate' : string,
}
export interface Container {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'containerType' : string,
  'updatedAt' : bigint,
  'stage' : string,
  'teamLeader' : string,
  'notes' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
}
export interface ContainerInput {
  'customerName' : string,
  'containerType' : string,
  'stage' : string,
  'teamLeader' : string,
  'notes' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
}
export interface Painting {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'stage' : string,
  'exteriorColour' : string,
  'notes' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'interiorColour' : string,
  'photos' : Array<Photo>,
}
export interface PaintingInput {
  'customerName' : string,
  'stage' : string,
  'exteriorColour' : string,
  'notes' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'interiorColour' : string,
  'photos' : Array<Photo>,
}
export interface Parking {
  'id' : bigint,
  'customerName' : string,
  'entryDate' : string,
  'waitingFor' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'notes' : string,
  'photos' : Array<Photo>,
}
export interface ParkingInput {
  'customerName' : string,
  'entryDate' : string,
  'waitingFor' : string,
  'notes' : string,
  'photos' : Array<Photo>,
}
export type Photo = Uint8Array;
export interface Underpart {
  'id' : bigint,
  'customerName' : string,
  'teamName' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'notes' : string,
  'workStatus' : string,
  'photos' : Array<Photo>,
}
export interface UnderpartInput {
  'customerName' : string,
  'teamName' : string,
  'notes' : string,
  'workStatus' : string,
  'photos' : Array<Photo>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCabin' : ActorMethod<[CabinInput], bigint>,
  'addContainer' : ActorMethod<[ContainerInput], bigint>,
  'addPainting' : ActorMethod<[PaintingInput], bigint>,
  'addParking' : ActorMethod<[ParkingInput], bigint>,
  'addUnderpart' : ActorMethod<[UnderpartInput], bigint>,
  'deleteCabin' : ActorMethod<[bigint], boolean>,
  'deleteContainer' : ActorMethod<[bigint], boolean>,
  'deletePainting' : ActorMethod<[bigint], boolean>,
  'deleteParking' : ActorMethod<[bigint], boolean>,
  'deleteUnderpart' : ActorMethod<[bigint], boolean>,
  'getCabins' : ActorMethod<[], Array<Cabin>>,
  'getContainers' : ActorMethod<[], Array<Container>>,
  'getPaintings' : ActorMethod<[], Array<Painting>>,
  'getParkings' : ActorMethod<[], Array<Parking>>,
  'getUnderparts' : ActorMethod<[], Array<Underpart>>,
  'login' : ActorMethod<[string, string], [] | [string]>,
  'updateCabin' : ActorMethod<[bigint, CabinInput], boolean>,
  'updateContainer' : ActorMethod<[bigint, ContainerInput], boolean>,
  'updatePainting' : ActorMethod<[bigint, PaintingInput], boolean>,
  'updateParking' : ActorMethod<[bigint, ParkingInput], boolean>,
  'updateUnderpart' : ActorMethod<[bigint, UnderpartInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];