/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cabin {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'stage' : string,
  'notes' : string,
  'customName' : string,
  'cabinType' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
  'startDate' : string,
}
export interface CabinInput {
  'customerName' : string,
  'stage' : string,
  'notes' : string,
  'customName' : string,
  'cabinType' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
  'startDate' : string,
}
export interface Container {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'containerType' : string,
  'updatedAt' : bigint,
  'stage' : string,
  'teamLeader' : string,
  'notes' : string,
  'customName' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
}
export interface ContainerInput {
  'customerName' : string,
  'containerType' : string,
  'stage' : string,
  'teamLeader' : string,
  'notes' : string,
  'customName' : string,
  'expectedDate' : string,
  'photos' : Array<Photo>,
}
export interface DailyUpdate {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'createdAt' : bigint,
  'monthLabel' : string,
  'section' : string,
  'delays' : string,
  'notes' : string,
  'weekLabel' : string,
  'shiftType' : string,
  'stageProgress' : string,
  'photos' : Array<Photo>,
  'workDone' : string,
}
export interface DailyUpdateInput {
  'status' : string,
  'date' : string,
  'monthLabel' : string,
  'section' : string,
  'delays' : string,
  'notes' : string,
  'weekLabel' : string,
  'shiftType' : string,
  'stageProgress' : string,
  'photos' : Array<Photo>,
  'workDone' : string,
}
export interface Delivery {
  'customerName' : string,
  'teamName' : string,
  'createdAt' : bigint,
  'deliveryDate' : string,
  'notes' : string,
  'customName' : string,
  'driverName' : string,
  'photos' : Array<Photo>,
  'vehicleNo' : string,
}
export interface DeliveryInput {
  'customerName' : string,
  'teamName' : string,
  'deliveryDate' : string,
  'notes' : string,
  'customName' : string,
  'driverName' : string,
  'photos' : Array<Photo>,
  'vehicleNo' : string,
}
export interface MonthlyArchive {
  'id' : bigint,
  'weekLabels' : Array<string>,
  'month' : bigint,
  'overallSummary' : string,
  'totalDelays' : bigint,
  'createdAt' : bigint,
  'year' : bigint,
  'monthLabel' : string,
  'totalUnderparts' : bigint,
  'totalParkings' : bigint,
  'totalCabins' : bigint,
  'totalContainers' : bigint,
  'totalPaintings' : bigint,
}
export interface MonthlyArchiveInput {
  'weekLabels' : Array<string>,
  'month' : bigint,
  'overallSummary' : string,
  'totalDelays' : bigint,
  'year' : bigint,
  'monthLabel' : string,
  'totalUnderparts' : bigint,
  'totalParkings' : bigint,
  'totalCabins' : bigint,
  'totalContainers' : bigint,
  'totalPaintings' : bigint,
}
export interface Painting {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'stage' : string,
  'exteriorColour' : string,
  'notes' : string,
  'customName' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'interiorColour' : string,
  'photos' : Array<Photo>,
}
export interface PaintingInput {
  'customerName' : string,
  'stage' : string,
  'exteriorColour' : string,
  'notes' : string,
  'customName' : string,
  'teamNo' : string,
  'expectedDate' : string,
  'interiorColour' : string,
  'photos' : Array<Photo>,
}
export interface Parking {
  'id' : bigint,
  'customerName' : string,
  'entryDate' : string,
  'waitingFor' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'notes' : string,
  'customName' : string,
  'photos' : Array<Photo>,
}
export interface ParkingInput {
  'customerName' : string,
  'entryDate' : string,
  'waitingFor' : string,
  'notes' : string,
  'customName' : string,
  'photos' : Array<Photo>,
}
export type Photo = Uint8Array;
export interface Underpart {
  'id' : bigint,
  'customerName' : string,
  'teamName' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'notes' : string,
  'customName' : string,
  'workStatus' : string,
  'photos' : Array<Photo>,
}
export interface UnderpartInput {
  'customerName' : string,
  'teamName' : string,
  'notes' : string,
  'customName' : string,
  'workStatus' : string,
  'photos' : Array<Photo>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyReport {
  'id' : bigint,
  'status' : string,
  'paintingSummary' : string,
  'month' : bigint,
  'weekEnd' : string,
  'cabinSummary' : string,
  'totalUpdates' : bigint,
  'containerSummary' : string,
  'createdAt' : bigint,
  'overallNotes' : string,
  'underpartsSummary' : string,
  'year' : bigint,
  'monthLabel' : string,
  'weekNumber' : bigint,
  'parkingSummary' : string,
  'weekLabel' : string,
  'weekStart' : string,
  'archivedAt' : bigint,
}
export interface WeeklyReportInput {
  'status' : string,
  'paintingSummary' : string,
  'month' : bigint,
  'weekEnd' : string,
  'cabinSummary' : string,
  'totalUpdates' : bigint,
  'containerSummary' : string,
  'overallNotes' : string,
  'underpartsSummary' : string,
  'year' : bigint,
  'monthLabel' : string,
  'weekNumber' : bigint,
  'parkingSummary' : string,
  'weekLabel' : string,
  'weekStart' : string,
}
export interface WorkOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'section' : string,
  'description' : string,
  'updatedAt' : bigint,
  'notes' : string,
  'assignedTeam' : string,
  'expectedDate' : string,
  'weekLabel' : string,
  'photos' : Array<Photo>,
}
export interface WorkOrderInput {
  'customerName' : string,
  'status' : string,
  'title' : string,
  'section' : string,
  'description' : string,
  'notes' : string,
  'assignedTeam' : string,
  'expectedDate' : string,
  'weekLabel' : string,
  'photos' : Array<Photo>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCabin' : ActorMethod<[CabinInput], undefined>,
  'addContainer' : ActorMethod<[ContainerInput], undefined>,
  'addDailyUpdate' : ActorMethod<[DailyUpdateInput], undefined>,
  'addDelivery' : ActorMethod<[DeliveryInput], undefined>,
  'addMonthlyArchive' : ActorMethod<[MonthlyArchiveInput], undefined>,
  'addPainting' : ActorMethod<[PaintingInput], undefined>,
  'addParking' : ActorMethod<[ParkingInput], undefined>,
  'addUnderpart' : ActorMethod<[UnderpartInput], undefined>,
  'addWeeklyReport' : ActorMethod<[WeeklyReportInput], undefined>,
  'addWorkOrder' : ActorMethod<[WorkOrderInput], undefined>,
  'archiveDailyUpdatesForWeek' : ActorMethod<[string], undefined>,
  'archiveWeeklyReportToMonth' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCabin' : ActorMethod<[bigint], undefined>,
  'deleteContainer' : ActorMethod<[bigint], undefined>,
  'deletePainting' : ActorMethod<[bigint], undefined>,
  'deleteParking' : ActorMethod<[bigint], undefined>,
  'deleteUnderpart' : ActorMethod<[bigint], undefined>,
  'deleteWorkOrder' : ActorMethod<[bigint], undefined>,
  'getCabins' : ActorMethod<[], Array<Cabin>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContainers' : ActorMethod<[], Array<Container>>,
  'getDailyUpdates' : ActorMethod<[], Array<DailyUpdate>>,
  'getDailyUpdatesByDate' : ActorMethod<[string], Array<DailyUpdate>>,
  'getDailyUpdatesByStatus' : ActorMethod<[string], Array<DailyUpdate>>,
  'getDailyUpdatesByWeek' : ActorMethod<[string], Array<DailyUpdate>>,
  'getDeliveries' : ActorMethod<[], Array<Delivery>>,
  'getMonthlyArchives' : ActorMethod<[], Array<MonthlyArchive>>,
  'getPaintings' : ActorMethod<[], Array<Painting>>,
  'getParkings' : ActorMethod<[], Array<Parking>>,
  'getUnderparts' : ActorMethod<[], Array<Underpart>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyReports' : ActorMethod<[], Array<WeeklyReport>>,
  'getWeeklyReportsByMonth' : ActorMethod<
    [bigint, bigint],
    Array<WeeklyReport>
  >,
  'getWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCabin' : ActorMethod<[bigint, CabinInput], undefined>,
  'updateContainer' : ActorMethod<[bigint, ContainerInput], undefined>,
  'updateMonthlyArchive' : ActorMethod<
    [bigint, MonthlyArchiveInput],
    undefined
  >,
  'updatePainting' : ActorMethod<[bigint, PaintingInput], undefined>,
  'updateParking' : ActorMethod<[bigint, ParkingInput], undefined>,
  'updateUnderpart' : ActorMethod<[bigint, UnderpartInput], undefined>,
  'updateWorkOrder' : ActorMethod<[bigint, WorkOrderInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];