/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Photo = IDL.Vec(IDL.Nat8);
export const CabinInput = IDL.Record({
  'stage' : IDL.Text,
  'notes' : IDL.Text,
  'cabinType' : IDL.Text,
  'teamNo' : IDL.Text,
  'expectedDate' : IDL.Text,
  'photos' : IDL.Vec(Photo),
  'startDate' : IDL.Text,
});
export const ContainerInput = IDL.Record({
  'customerName' : IDL.Text,
  'containerType' : IDL.Text,
  'stage' : IDL.Text,
  'teamLeader' : IDL.Text,
  'notes' : IDL.Text,
  'expectedDate' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});
export const PaintingInput = IDL.Record({
  'customerName' : IDL.Text,
  'stage' : IDL.Text,
  'exteriorColour' : IDL.Text,
  'notes' : IDL.Text,
  'teamNo' : IDL.Text,
  'expectedDate' : IDL.Text,
  'interiorColour' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});
export const ParkingInput = IDL.Record({
  'customerName' : IDL.Text,
  'entryDate' : IDL.Text,
  'waitingFor' : IDL.Text,
  'notes' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});
export const UnderpartInput = IDL.Record({
  'customerName' : IDL.Text,
  'teamName' : IDL.Text,
  'notes' : IDL.Text,
  'workStatus' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});
export const Cabin = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'stage' : IDL.Text,
  'notes' : IDL.Text,
  'cabinType' : IDL.Text,
  'teamNo' : IDL.Text,
  'expectedDate' : IDL.Text,
  'photos' : IDL.Vec(Photo),
  'startDate' : IDL.Text,
});
export const Container = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'containerType' : IDL.Text,
  'updatedAt' : IDL.Int,
  'stage' : IDL.Text,
  'teamLeader' : IDL.Text,
  'notes' : IDL.Text,
  'expectedDate' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});
export const Painting = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'stage' : IDL.Text,
  'exteriorColour' : IDL.Text,
  'notes' : IDL.Text,
  'teamNo' : IDL.Text,
  'expectedDate' : IDL.Text,
  'interiorColour' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});
export const Parking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'entryDate' : IDL.Text,
  'waitingFor' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});
export const Underpart = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'teamName' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'workStatus' : IDL.Text,
  'photos' : IDL.Vec(Photo),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCabin' : IDL.Func([CabinInput], [IDL.Nat], []),
  'addContainer' : IDL.Func([ContainerInput], [IDL.Nat], []),
  'addPainting' : IDL.Func([PaintingInput], [IDL.Nat], []),
  'addParking' : IDL.Func([ParkingInput], [IDL.Nat], []),
  'addUnderpart' : IDL.Func([UnderpartInput], [IDL.Nat], []),
  'deleteCabin' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteContainer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePainting' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteParking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteUnderpart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCabins' : IDL.Func([], [IDL.Vec(Cabin)], ['query']),
  'getContainers' : IDL.Func([], [IDL.Vec(Container)], ['query']),
  'getPaintings' : IDL.Func([], [IDL.Vec(Painting)], ['query']),
  'getParkings' : IDL.Func([], [IDL.Vec(Parking)], ['query']),
  'getUnderparts' : IDL.Func([], [IDL.Vec(Underpart)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'updateCabin' : IDL.Func([IDL.Nat, CabinInput], [IDL.Bool], []),
  'updateContainer' : IDL.Func([IDL.Nat, ContainerInput], [IDL.Bool], []),
  'updatePainting' : IDL.Func([IDL.Nat, PaintingInput], [IDL.Bool], []),
  'updateParking' : IDL.Func([IDL.Nat, ParkingInput], [IDL.Bool], []),
  'updateUnderpart' : IDL.Func([IDL.Nat, UnderpartInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Photo = IDL.Vec(IDL.Nat8);
  const CabinInput = IDL.Record({
    'stage' : IDL.Text,
    'notes' : IDL.Text,
    'cabinType' : IDL.Text,
    'teamNo' : IDL.Text,
    'expectedDate' : IDL.Text,
    'photos' : IDL.Vec(Photo),
    'startDate' : IDL.Text,
  });
  const ContainerInput = IDL.Record({
    'customerName' : IDL.Text,
    'containerType' : IDL.Text,
    'stage' : IDL.Text,
    'teamLeader' : IDL.Text,
    'notes' : IDL.Text,
    'expectedDate' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  const PaintingInput = IDL.Record({
    'customerName' : IDL.Text,
    'stage' : IDL.Text,
    'exteriorColour' : IDL.Text,
    'notes' : IDL.Text,
    'teamNo' : IDL.Text,
    'expectedDate' : IDL.Text,
    'interiorColour' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  const ParkingInput = IDL.Record({
    'customerName' : IDL.Text,
    'entryDate' : IDL.Text,
    'waitingFor' : IDL.Text,
    'notes' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  const UnderpartInput = IDL.Record({
    'customerName' : IDL.Text,
    'teamName' : IDL.Text,
    'notes' : IDL.Text,
    'workStatus' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  const Cabin = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'stage' : IDL.Text,
    'notes' : IDL.Text,
    'cabinType' : IDL.Text,
    'teamNo' : IDL.Text,
    'expectedDate' : IDL.Text,
    'photos' : IDL.Vec(Photo),
    'startDate' : IDL.Text,
  });
  const Container = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'containerType' : IDL.Text,
    'updatedAt' : IDL.Int,
    'stage' : IDL.Text,
    'teamLeader' : IDL.Text,
    'notes' : IDL.Text,
    'expectedDate' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  const Painting = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'stage' : IDL.Text,
    'exteriorColour' : IDL.Text,
    'notes' : IDL.Text,
    'teamNo' : IDL.Text,
    'expectedDate' : IDL.Text,
    'interiorColour' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  const Parking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'entryDate' : IDL.Text,
    'waitingFor' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  const Underpart = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'teamName' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'workStatus' : IDL.Text,
    'photos' : IDL.Vec(Photo),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCabin' : IDL.Func([CabinInput], [IDL.Nat], []),
    'addContainer' : IDL.Func([ContainerInput], [IDL.Nat], []),
    'addPainting' : IDL.Func([PaintingInput], [IDL.Nat], []),
    'addParking' : IDL.Func([ParkingInput], [IDL.Nat], []),
    'addUnderpart' : IDL.Func([UnderpartInput], [IDL.Nat], []),
    'deleteCabin' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteContainer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePainting' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteParking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteUnderpart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCabins' : IDL.Func([], [IDL.Vec(Cabin)], ['query']),
    'getContainers' : IDL.Func([], [IDL.Vec(Container)], ['query']),
    'getPaintings' : IDL.Func([], [IDL.Vec(Painting)], ['query']),
    'getParkings' : IDL.Func([], [IDL.Vec(Parking)], ['query']),
    'getUnderparts' : IDL.Func([], [IDL.Vec(Underpart)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'updateCabin' : IDL.Func([IDL.Nat, CabinInput], [IDL.Bool], []),
    'updateContainer' : IDL.Func([IDL.Nat, ContainerInput], [IDL.Bool], []),
    'updatePainting' : IDL.Func([IDL.Nat, PaintingInput], [IDL.Bool], []),
    'updateParking' : IDL.Func([IDL.Nat, ParkingInput], [IDL.Bool], []),
    'updateUnderpart' : IDL.Func([IDL.Nat, UnderpartInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };