/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Photo = Uint8Array;
export interface Cabin {
    id: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    stage: string;
    notes: string;
    cabinType: string;
    teamNo: string;
    expectedDate: string;
    photos: Array<Photo>;
    startDate: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaintingInput {
    customerName: string;
    stage: string;
    exteriorColour: string;
    notes: string;
    teamNo: string;
    expectedDate: string;
    interiorColour: string;
    photos: Array<Photo>;
}
export interface UnderpartInput {
    customerName: string;
    teamName: string;
    notes: string;
    workStatus: string;
    photos: Array<Photo>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Parking {
    id: bigint;
    customerName: string;
    entryDate: string;
    waitingFor: string;
    createdAt: bigint;
    updatedAt: bigint;
    notes: string;
    photos: Array<Photo>;
}
export interface ContainerInput {
    customerName: string;
    containerType: string;
    stage: string;
    teamLeader: string;
    notes: string;
    expectedDate: string;
    photos: Array<Photo>;
}
export interface ParkingInput {
    customerName: string;
    entryDate: string;
    waitingFor: string;
    notes: string;
    photos: Array<Photo>;
}
export interface Container {
    id: bigint;
    customerName: string;
    createdAt: bigint;
    containerType: string;
    updatedAt: bigint;
    stage: string;
    teamLeader: string;
    notes: string;
    expectedDate: string;
    photos: Array<Photo>;
}
export interface Painting {
    id: bigint;
    customerName: string;
    createdAt: bigint;
    updatedAt: bigint;
    stage: string;
    exteriorColour: string;
    notes: string;
    teamNo: string;
    expectedDate: string;
    interiorColour: string;
    photos: Array<Photo>;
}
export interface Underpart {
    id: bigint;
    customerName: string;
    teamName: string;
    createdAt: bigint;
    updatedAt: bigint;
    notes: string;
    workStatus: string;
    photos: Array<Photo>;
}
export interface CabinInput {
    stage: string;
    notes: string;
    cabinType: string;
    teamNo: string;
    expectedDate: string;
    photos: Array<Photo>;
    startDate: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addCabin(input: CabinInput): Promise<bigint>;
    addContainer(input: ContainerInput): Promise<bigint>;
    addPainting(input: PaintingInput): Promise<bigint>;
    addParking(input: ParkingInput): Promise<bigint>;
    addUnderpart(input: UnderpartInput): Promise<bigint>;
    deleteCabin(id: bigint): Promise<boolean>;
    deleteContainer(id: bigint): Promise<boolean>;
    deletePainting(id: bigint): Promise<boolean>;
    deleteParking(id: bigint): Promise<boolean>;
    deleteUnderpart(id: bigint): Promise<boolean>;
    getCabins(): Promise<Array<Cabin>>;
    getContainers(): Promise<Array<Container>>;
    getPaintings(): Promise<Array<Painting>>;
    getParkings(): Promise<Array<Parking>>;
    getUnderparts(): Promise<Array<Underpart>>;
    login(email: string, password: string): Promise<string | null>;
    updateCabin(id: bigint, input: CabinInput): Promise<boolean>;
    updateContainer(id: bigint, input: ContainerInput): Promise<boolean>;
    updatePainting(id: bigint, input: PaintingInput): Promise<boolean>;
    updateParking(id: bigint, input: ParkingInput): Promise<boolean>;
    updateUnderpart(id: bigint, input: UnderpartInput): Promise<boolean>;
}
import type { _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addCabin(arg0: CabinInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCabin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCabin(arg0);
            return result;
        }
    }
    async addContainer(arg0: ContainerInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addContainer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContainer(arg0);
            return result;
        }
    }
    async addPainting(arg0: PaintingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPainting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPainting(arg0);
            return result;
        }
    }
    async addParking(arg0: ParkingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addParking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParking(arg0);
            return result;
        }
    }
    async addUnderpart(arg0: UnderpartInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addUnderpart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUnderpart(arg0);
            return result;
        }
    }
    async deleteCabin(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCabin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCabin(arg0);
            return result;
        }
    }
    async deleteContainer(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContainer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContainer(arg0);
            return result;
        }
    }
    async deletePainting(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePainting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePainting(arg0);
            return result;
        }
    }
    async deleteParking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParking(arg0);
            return result;
        }
    }
    async deleteUnderpart(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUnderpart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUnderpart(arg0);
            return result;
        }
    }
    async getCabins(): Promise<Array<Cabin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCabins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCabins();
            return result;
        }
    }
    async getContainers(): Promise<Array<Container>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContainers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContainers();
            return result;
        }
    }
    async getPaintings(): Promise<Array<Painting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaintings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaintings();
            return result;
        }
    }
    async getParkings(): Promise<Array<Parking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParkings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParkings();
            return result;
        }
    }
    async getUnderparts(): Promise<Array<Underpart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnderparts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnderparts();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCabin(arg0: bigint, arg1: CabinInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCabin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCabin(arg0, arg1);
            return result;
        }
    }
    async updateContainer(arg0: bigint, arg1: ContainerInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContainer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContainer(arg0, arg1);
            return result;
        }
    }
    async updatePainting(arg0: bigint, arg1: PaintingInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePainting(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePainting(arg0, arg1);
            return result;
        }
    }
    async updateParking(arg0: bigint, arg1: ParkingInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParking(arg0, arg1);
            return result;
        }
    }
    async updateUnderpart(arg0: bigint, arg1: UnderpartInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUnderpart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUnderpart(arg0, arg1);
            return result;
        }
    }
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
